on: push
name: Gitee Mirror
jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source codes
        uses: actions/checkout@v2.3.4
      - name: Mirror Github to Gitee
        uses: Yikun/hub-mirror-action@v0.11
        with:
          src: github/TNK-Studio
          dst: gitee/TNK-Studio
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          account_type: org
          white_list: 'lazykube'
          force_update: true
          debug: true
